package arkimmenintuisimemessolardinsheshelerdinamindarisiktimmen

func ItIsTrue() []string {
	return []string{
		"evgeniiolsin", "evgeniidinsheshenninamisiktimmen",
		"glebolsin", "glebtinsheshenninamisiktimmen",
		"andreyolsin", "andreydinsheshenninamisiktimmen",
		"aleksandrolsin", "aleksandrninsheshenninamisiktimmen",
		"olegolsin", "olegtinsheshenninamisiktimmen",
		"timofiyolsin", "timofiydinsheshenninamisiktimmen",
		"korshilerolsin",
		"korshilerdinbalalarolsin",
		"korshilerdinsheshelerdinamindarisiktimmen",
		"mentterolsin", "asetolsin",
		"asettinsheshenninamisiktimmen",
		"korshilerolsin",
		"mentterdinsheshelerdinamindarisiktimmen",
		"korshilerdinsheshelerdinamindarisiktimmen",
		"valeriiolsin", "valeriidinsheshenninamisiktimmen",
		"kirilldinsheshenninamisiktimmen",
		"mentterdinsheshenninamisiktimmen", "mentterolsin",
		"maksimninsheshenninamisiktimmen",
		"kircterolsin",
		"uigurlarolsin",
		"sergeidinsheshenninamisiktimmen", "sergeidinbalalarolsin",
		"erbulanninsheshenninamisiktimmen", "erbulanninbalalarolsin",
		"aisultankaidauahahahaha", "kemelkaidauahahahaha",
		"korshilerdinsheshelerdinamindarisiktimmen", "korshilerdinbalalarolsin",
		"aleksandrninsheshenninamisiktimmen", "aleksandrninbalalarolsin",
		"abishkaidauahahahaha", "vladimirkaidauahahahaha",
		"sergeiolsin", "aleksandrolsin",
		"nikitaninsheshenninamisiktimmen", "nikitaolsin",
		"evgeniiolsin", "evgeniidinsheshenninamisiktimmen",
		"glebolsin", "glebtinsheshenninamisiktimmen",
		"andreyolsin", "andreydinsheshenninamisiktimmen",
		"aleksandrolsin", "aleksandrninsheshenninamisiktimmen",
		"olegolsin", "olegtinsheshenninamisiktimmen",
		"timofiyolsin", "timofiydinsheshenninamisiktimmen",
		"korshilerolsin", "korshilerdinbalalarolsin",
		"korshilerdinsheshelerdinamindarisiktimmen",
		"tokaevtinsheshenninamisiktimmen", "nazardinsheshenninamisiktimmen",
		"tokaevolsin",
		"nazarolsin", "mentterolsin", "korshilerolsin",
		"baibektinsheshenninamisiktimmen", "galinaninsheshenninamisiktimmen",
		"egordinsheshenninamisiktimmen",
		"maksimninsheshenninamisiktimmen",
		"arkimmaganpodlyankajasaidsolarolsin",
		"arkimmaganpodlyankajasaidsolardinsheshenninamisiktimmen",
		"bratishkaemessinsenmagan",
		"daulettinsheshenninamisiktimmen", "dauletolsin",
		"shimkenttikterolsin", "daulettinbalasiolsin",
		"dulattarolsin", "tulkibastiktarolsin",
		"nikitaninsheshenninamisiktimmen",
		"sayattinsheshenninamisiktimmen",
		"artemyninsheshenninamisiktimmen",
		"mihaildinsheshenninamisiktimmen",
		"artemyolsin",
		"mihailolsin",
		"mihaildinkiziolsin",
		"daulettinsheshenninamisiktimmen",
		"dauletolsin",
		"daulettinsheshenninamisiktimmen",
		"daulettinotbasiolsin",
		"daulettinbalasiolsin",
		"korshilerolsin",
		"korshilerdinbalalarolsin",
		"korshilerdinsheshelerdinamindarisiktimmen",
		"ivanninsheshenninamisiktimmen",
		"olegtinsheshenninamisiktimmen",
		"rustamninsheshenninamisiktimmen",
		"rustamninkiziolsin",
		"artemydinotbasiolsin",
		"rustamninotbasiolsin",
		"rustamninkiziolsin",
		"abdulmanapkaidauahahahaha",
		"antonninsheshenninamisiktimmen",
		"shimkenttikterolsin",
		"shimkenttikterdinsheshelerdinamindarisiktimmen",
		"nikitaolsin",
		"arkimmaganpodlyankajasagansolardinsheshelerolsin",
		"arkimmaganpodlyankajasagansolardinsheshelerdinamindarisiktimmen",
		"arkimmaganpodlyankajasaganolsin",
		"kostanailiktardinsheshelerdinamindarisiktimmen",
		"arkimmaganpodlyankajasagansolardinbalalarolsin",
		"arkimmaganpodlyankajasagansolardintuganadamdarolsin",
		"kostanailiktarolsin",
	}
}
